# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lemmatizer.proto import lemmatizer_pb2 as lemmatizer_dot_proto_dot_lemmatizer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lemmatizer/proto/lemmatizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LemmatizerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Lemmatize = channel.unary_unary(
                '/lemmatizer.v1.LemmatizerService/Lemmatize',
                request_serializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeRequest.SerializeToString,
                response_deserializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmaResult.FromString,
                _registered_method=True)
        self.LemmatizeBatch = channel.unary_unary(
                '/lemmatizer.v1.LemmatizerService/LemmatizeBatch',
                request_serializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeBatchRequest.SerializeToString,
                response_deserializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeBatchResponse.FromString,
                _registered_method=True)


class LemmatizerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Lemmatize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LemmatizeBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LemmatizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Lemmatize': grpc.unary_unary_rpc_method_handler(
                    servicer.Lemmatize,
                    request_deserializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeRequest.FromString,
                    response_serializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmaResult.SerializeToString,
            ),
            'LemmatizeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.LemmatizeBatch,
                    request_deserializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeBatchRequest.FromString,
                    response_serializer=lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lemmatizer.v1.LemmatizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lemmatizer.v1.LemmatizerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LemmatizerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Lemmatize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemmatizer.v1.LemmatizerService/Lemmatize',
            lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeRequest.SerializeToString,
            lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmaResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LemmatizeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lemmatizer.v1.LemmatizerService/LemmatizeBatch',
            lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeBatchRequest.SerializeToString,
            lemmatizer_dot_proto_dot_lemmatizer__pb2.LemmatizeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
