# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lemmatizer/proto/lemmatizer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lemmatizer/proto/lemmatizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!lemmatizer/proto/lemmatizer.proto\x12\rlemmatizer.v1\"2\n\x10LemmatizeRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"G\n\x15LemmatizeBatchRequest\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.lemmatizer.v1.LemmatizeRequest\"E\n\x16LemmatizeBatchResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.lemmatizer.v1.LemmaResult\"z\n\x0bLemmaResult\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x17\n\x0f\x65lapsed_seconds\x18\x02 \x01(\x01\x12\x15\n\runique_lemmas\x18\x03 \x03(\t\x12)\n\x06tokens\x18\x04 \x03(\x0b\x32\x19.lemmatizer.v1.LemmaToken\"\\\n\nLemmaToken\x12\x0f\n\x07surface\x18\x01 \x01(\t\x12\r\n\x05lemma\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x04 \x01(\t\x12\x0b\n\x03pos\x18\x05 \x01(\t2\xbc\x01\n\x11LemmatizerService\x12H\n\tLemmatize\x12\x1f.lemmatizer.v1.LemmatizeRequest\x1a\x1a.lemmatizer.v1.LemmaResult\x12]\n\x0eLemmatizeBatch\x12$.lemmatizer.v1.LemmatizeBatchRequest\x1a%.lemmatizer.v1.LemmatizeBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lemmatizer.proto.lemmatizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEMMATIZEREQUEST']._serialized_start=52
  _globals['_LEMMATIZEREQUEST']._serialized_end=102
  _globals['_LEMMATIZEBATCHREQUEST']._serialized_start=104
  _globals['_LEMMATIZEBATCHREQUEST']._serialized_end=175
  _globals['_LEMMATIZEBATCHRESPONSE']._serialized_start=177
  _globals['_LEMMATIZEBATCHRESPONSE']._serialized_end=246
  _globals['_LEMMARESULT']._serialized_start=248
  _globals['_LEMMARESULT']._serialized_end=370
  _globals['_LEMMATOKEN']._serialized_start=372
  _globals['_LEMMATOKEN']._serialized_end=464
  _globals['_LEMMATIZERSERVICE']._serialized_start=467
  _globals['_LEMMATIZERSERVICE']._serialized_end=655
# @@protoc_insertion_point(module_scope)
